const datos = [

    // ==============================================
    // HUAWEI
    // ==============================================
    { modelos: "P SMART", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 33000 },
    { modelos: "P SMART + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 39000 },
    { modelos: "P SMART 2019", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 35000 },
    { modelos: "P SMART 2019 + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 41000 },
    { modelos: "P8", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 33000 },
    { modelos: "P8 LITE", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 26000 },
    { modelos: "P10", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 35000 },
    { modelos: "P10 LITE", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 35000 },
    { modelos: "P20", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 43000 },
    { modelos: "P20 LITE", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 35000 },
    { modelos: "P20 LITE + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 41000 },
    { modelos: "P30 LITE", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 41000 },
    { modelos: "P30 LITE + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 47000 },
    { modelos: "P40 LITE", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 41000 },
    { modelos: "P40 LITE + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 47000 },
    { modelos: "Y3 2017", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 33000 },{ modelos: "Y5 2018", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 33000 },
{ modelos: "Y5 2019", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 33000 },
{ modelos: "Y6 2018", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 36000 },
{ modelos: "Y6 PRIME 2019", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 36000 },
{ modelos: "Y6 PRIME 2019 + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 42000 },
{ modelos: "Y6P", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 38000 },
{ modelos: "Y7 2018", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 33000 },
{ modelos: "Y7 2018 + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 38000 },
{ modelos: "Y7 PRIME 2019", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 36000 },
{ modelos: "Y7 PRIME 2019 + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 42000 },
{ modelos: "Y7P", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 38000 },
{ modelos: "Y7P + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 46000 },
{ modelos: "Y7A", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 38000 },
{ modelos: "Y8S + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 46000 },
{ modelos: "Y9 2018", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 34000 },
{ modelos: "Y9 2019/Y8S", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 40000 },
{ modelos: "Y9 2019 + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 46000 },
{ modelos: "Y9 PRIME 2019", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 42000 },
{ modelos: "Y9 PRIME 2019 + MARCO", categoria: "HUAWEI", subcategoria: "CON MARCO", precios: 50000 },
{ modelos: "Y9S", categoria: "HUAWEI", subcategoria: "SIN MARCO", precios: 42000 }];
